# remap prefix from C-b to C-a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# normal colors
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# start windows from 1
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# split paneles using | and -
unbind '"'
unbind %
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# switch panels using Alt-arrow
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# switch windows uning Ctrl+Alt+arrow
bind -n C-M-Left  previous-window
bind -n C-M-Right next-window

# mouse mode
set -g mouse on

# reload config file
bind r source-file ~/.config/tmux/tmux.conf \; display "Reloaded!"

# clear history
bind -n C-l send-keys C-l \; clear-history

# vim tweaks
set -s escape-time 0
set -g focus-events on

# theme
set -g @rose_pine_variant 'moon'
set -g @rose_pine_host 'off'
set -g @rose_pine_directory 'off'
set -g @rose_pine_date_time '%H:%M'
set -g @rose_pine_bar_bg_disable 'on'
set -g @rose_pine_bar_bg_disabled_color_option 'default'
set -g @rose_pine_window_status_separator "  "
set -g @rose_pine_show_current_program 'on'
set -g @rose_pine_disable_active_window_menu 'on'

# resurrect plugin
set -g @resurrect-strategy-vim 'session'
set -g @resurrect-strategy-nvim 'session'

# others
set -g status-interval 5
setw -g aggressive-resize on
set-environment -g TMUX_FZF_LAUNCH_KEY "C-f"
set -g @sessionx-bind 'o'

# plugins
set -g @plugin 'RyanMacG/tpm-redux'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'noscript/tmux-mighty-scroll'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'rose-pine/tmux'

run '~/.config/tmux/plugins/tpm-redux/tpm'

